### PR TITLE
Add random question button

### PR DESCRIPTION
**Pull request by sebastsg**
Adds a button to the instructor controls that starts a random question.

### CODE REVIEW

**Comment by hgeorgsch** [comment]
The random button seems to work fine for one random question, but nothing prevents repetition if it is used twice.  I think it is ok to merge it in, but I expect more demands ...

**Comment by sebastsg** [comment]
@hgeorgsch Only unasked questions will now be picked. If all have been asked, then any question will be picked.

**Review by andstor — APPROVED** [review]

**Comment by pejhab** [comment]
I finally got the time to play around with the development version, and - sorry - it simply does not work. Nothing happens when I choose questions from a certain category and click on "Add to quiz".

**Comment by pejhab** [comment]
I also not see the point of having the "with the selected" version included.  

jazzquiz-developmental-20210428

**Comment by pejhab** [comment]
Just to make sure you have seen my first message (about the "add to quiz" button not working,..

**Comment by hgeorgsch** [comment]
It says «With selected» because each of the three buttons refers to the selection made in the list above.  The drop-down menu where you have chosen «QC: General Areas A1» relates only to the «Move to >>» button, and mark the destination if you want to move selected questions to a different category.  I can see that this is unclear, so I have created a new issue on this specifically #71 .

The button to run a random question appears in the teacher interface when you start the quiz.  Instead of selecting the next question, or a question from a drop-down menu, you can now also select a random question.  Maybe this was not quite the feature you had expected!?

**Comment by hgeorgsch** [comment]
P.S.  I meant to write a little bit more, but since I saw your posting @pejhab , I posted what I had straight away.
It would be useful to see, in a new issue, your suggestion about what the UI/workflow should look like.

**Comment by hgeorgsch** [comment]
BTW.  The «add to quiz» button works for me.  It adds the questions selected in the list above.  It sounds as if you expect it to add all the questions from the selected category in the drop-down above the button, but this is not the intention.

**Comment by pejhab** [comment]
The most practical and intuitive work flow to me would be for the quiz to draw random questions from a category that I choose without the need to "add" them to the quiz. 

However, if this is not incompatible with the way the plugin is designed, the present approach of "adding" the questions to the quiz would do the job. 

And...

The "add to quiz" button does not work for me. I select some questions (from a category) and then click on "add to quiz" but nothing happens.

**Comment by hgeorgsch** [comment]
Please continue the discussion under the new issues.  This one has been closed, and will normally be overlooked.

**Pull request merged**
