### PR TITLE
Merge request #97

### PR DESCRIPTION
**Pull request by jorgenfinsveen**
Resolved issue by adding the question text column and implementing a function which determines whether to display the column or not in the question bank view

### CODE REVIEW

**Comment by hgeorgsch** [comment]
The question question text column cannot be turned off, even if No is selected in the dropdown.

**Comment by jorgenfinsveen** [comment]
Re-tested this now for Moodle version 4.1 and 4.3 using both Safari and Google Chrome. Worked every time I tested

**Comment by hgeorgsch** [comment]
OK.  Do you know if I need to do something to regenerate CSS files?
I saw some suspicious code suggesting that I had old CSS code.

**Comment by hgeorgsch** [comment]
Sorry. My fault. Got it now.

**Pull request merged**
